version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.301-sdk
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
